- id: 94aed283-f9c7-4740-8c72-8f9e8abb72ac
  owner: connor
  title: Add server support
  description: Right new we are only saving to a local task.yml file. While this is
    ok because we can leverage git to save and distribute the tasks we should also
    add server support so that we can have the tasks independent from the rest of
    the files that you are working in.
  tags: []
  complete: false
